### ISSUE TITLE
Homepage Responsiveness (Description is cut off by footer; resizing necessary)

### ISSUE THREAD

**Issue by coren-frankel** [m-smith15/webdev_flashcards#11]
On my last visit to the Homepage, I noticed that the text on the right side of the page is just barely cut off on my 100% view on a 13" laptop. 
Consider adapting with percentage values for size properties.

I will host a screenshot [here](https://share.getcloudapp.com/YEuDxbep) until the issue is resolved.

**Comment by m-smith15** [comment]
I put too much fluff in the footer when I initially set it up because it looks a little sparse.

When we talked about this, we mentioned a few different approaches:
 - sizing down the footer so its a little more succinct 
 - adding some margin to the top to make sure that nothing is cut off by it (home screen "about" section; view all bottom cards)
 
 OR
 - We might have to eventually, so could just build out an acknowledgements view now

I think for now, I'm going to go with option 1, sizing down the footer a tad and looking to add a little spacing to push it further down past any content that could be blocking it
